### ISSUE TITLE
Question about licensing

### ISSUE THREAD

**Issue by Kautenja** [sxpro/ImageEnhance_cGAN#1]
Hi, this is a great project! I'm wondering about the licensing of this code-base. There is no license provided in your repository currently, but I see that this code is based on [CSRNet](https://github.com/hejingwenhejingwen/CSRNet), which is in turn based on [mmsr](https://github.com/open-mmlab/mmediting), which is licensed as Apache Version 2.0. Would you mind uploading a LICENSE file to the repository to clarify?

**Comment by sxpro** [comment]
OK

**Comment by Kautenja** [comment]
Thanks!
